"""Run the harness as a background service via launchd (macOS).

`harness run` in a terminal dies with the terminal. A real install wants the
loop supervised and restarted across logout and reboot, which on macOS means a
LaunchAgent in `~/Library/LaunchAgents`.

Two pure builders (`wrapper_script`, `plist_bytes`) produce the files, so the
content is unit-testable without touching the disk or `launchctl`; the thin
`subprocess` shell around `launchctl` is the only untested part, mirroring how
`git_workspace` treats the system `git`.

The wrapper exists because launchd starts a process with almost no environment:
no `PATH` to `git`/`claude`, and none of the shell's `GITHUB_TOKEN`. Rather
than copy a token into a plist (a world-readable file in the user's home), the
wrapper borrows the one `gh` already keeps in the system keyring.
"""

from __future__ import annotations

import plistlib
import subprocess
import time
from pathlib import Path

DEFAULT_LABEL = "com.harness"


class ServiceError(RuntimeError):
    """A service operation failed. Carries the command and its stderr."""


def agents_dir(home: Path) -> Path:
    """Where a user's LaunchAgents live."""
    return home / "Library" / "LaunchAgents"


def plist_path(home: Path, label: str) -> Path:
    return agents_dir(home) / f"{label}.plist"


def wrapper_script(
    *,
    harness: Path,
    root: Path,
    api_port: int,
    path_entries: list[str],
    env_file: Path,
) -> str:
    """The shell wrapper launchd executes.

    Two credentials, neither in the plist:

    - `CLAUDE_CODE_OAUTH_TOKEN` — the load-bearing one. Under launchd, `claude`
      cannot read the login Keychain where an interactive `claude /login` stores
      its credential, so every agent step fails with "Not logged in". A token
      from `claude setup-token`, passed through the environment, makes `claude`
      bypass the keychain entirely. It lives in `env_file` (a 0600 file), which
      the wrapper sources.
    - `GITHUB_TOKEN` — an explicit value (from `env_file`) wins, otherwise
      `gh auth token` reads the keyring.

    A missing token of either kind warns rather than aborts: without the claude
    token agent steps fail (loudly, per task), without the GitHub token issue
    ingestion is simply off — the harness still serves `harness submit`.
    """
    path = ":".join(path_entries)
    return f"""#!/usr/bin/env bash
#
# Generated by `harness service install` — regenerated on every install.
# Edit the install command, not this file.

set -euo pipefail

export PATH="{path}"

# Machine-local secrets: 0600, never committed, never in the plist. This is
# where CLAUDE_CODE_OAUTH_TOKEN belongs — `claude` under launchd cannot reach
# the login Keychain, so a background run needs the token in the environment.
ENV_FILE="{env_file}"
if [ -f "$ENV_FILE" ]; then
    set -a
    . "$ENV_FILE"
    set +a
fi

if [ -z "${{CLAUDE_CODE_OAUTH_TOKEN:-}}" ]; then
    echo "warning: CLAUDE_CODE_OAUTH_TOKEN is not set. Under launchd, claude" \\
         "cannot read the macOS keychain, so every agent step will fail. Run" \\
         "'claude setup-token' and put CLAUDE_CODE_OAUTH_TOKEN=<token> in" \\
         "$ENV_FILE, then restart the service." >&2
fi

# GitHub token: an explicit value (possibly from ENV_FILE) wins, else the gh keyring.
if [ -z "${{GITHUB_TOKEN:-}}" ] && command -v gh >/dev/null 2>&1; then
    GITHUB_TOKEN="$(gh auth token 2>/dev/null || true)"
    export GITHUB_TOKEN
fi

if [ -z "${{GITHUB_TOKEN:-}}" ]; then
    echo "warning: no GITHUB_TOKEN and 'gh auth token' gave nothing —" \\
         "GitHub issue ingestion is disabled; 'harness submit' still works." >&2
fi

exec "{harness}" run --root "{root}" --api-port {api_port}
"""


def plist_bytes(
    *,
    label: str,
    wrapper: Path,
    working_dir: Path,
    log_dir: Path,
    home: Path,
) -> bytes:
    """The LaunchAgent definition, built with stdlib plistlib (never hand-rolled XML).

    `KeepAlive` restarts the loop if it dies; `RunAtLoad` starts it at login.
    The plist deliberately carries no secrets — see `wrapper_script`.
    """
    definition = {
        "Label": label,
        "ProgramArguments": ["/bin/bash", str(wrapper)],
        "RunAtLoad": True,
        "KeepAlive": True,
        "WorkingDirectory": str(working_dir),
        "StandardOutPath": str(log_dir / "harness.log"),
        "StandardErrorPath": str(log_dir / "harness.error.log"),
        "EnvironmentVariables": {"HOME": str(home)},
    }
    return plistlib.dumps(definition)


def autoupdate_plist_bytes(
    *,
    label: str,
    harness: Path,
    service_label: str,
    hours: list[int],
    path_entries: list[str],
    log_dir: Path,
    home: Path,
) -> bytes:
    """A LaunchAgent that runs `harness update --restart --only-if-idle` on a
    schedule, so the box stays current without interrupting a running stage.

    `StartCalendarInterval` fires at each of `hours` (minute 0). No `KeepAlive`:
    this is a periodic one-shot, not a daemon. `--only-if-idle` is what makes a
    firing that lands mid-stage skip the restart and leave it for the next slot.
    """
    definition = {
        "Label": label,
        "ProgramArguments": [
            str(harness),
            "update",
            "--restart",
            "--only-if-idle",
            "--label",
            service_label,
        ],
        "StartCalendarInterval": [{"Hour": h, "Minute": 0} for h in hours],
        "StandardOutPath": str(log_dir / "autoupdate.log"),
        "StandardErrorPath": str(log_dir / "autoupdate.log"),
        "EnvironmentVariables": {"HOME": str(home), "PATH": ":".join(path_entries)},
    }
    return plistlib.dumps(definition)


def _launchctl(args: list[str], *, check: bool = True) -> subprocess.CompletedProcess:
    try:
        result = subprocess.run(
            ["launchctl", *args], capture_output=True, text=True, check=False
        )
    except OSError as error:  # launchctl missing => not a Mac, or a broken one
        raise ServiceError(f"could not run launchctl: {error}") from error
    if check and result.returncode != 0:
        raise ServiceError(
            f"launchctl {' '.join(args)} failed (exit {result.returncode}): "
            f"{result.stderr.strip()}"
        )
    return result


def _wait_until_unloaded(uid: int, label: str, timeout: float = 10.0) -> bool:
    """Block until launchd has really dropped the label. True if it is gone.

    `bootout` returns before the job is actually torn down, so a `bootstrap`
    issued straight afterwards hits the still-loaded label and fails with
    "Bootstrap failed: 5: Input/output error". Polling `print` is the only
    reliable signal that the old copy is gone.
    """
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if status(uid, label) is None:
            return True
        time.sleep(0.2)
    return status(uid, label) is None


def load(uid: int, path: Path, label: str) -> None:
    """(Re)load the agent. Boots out a previous copy first so install is idempotent."""
    domain = f"gui/{uid}"
    _launchctl(["bootout", f"{domain}/{label}"], check=False)  # absent is fine
    if not _wait_until_unloaded(uid, label):
        raise ServiceError(
            f"{label} is still loaded after bootout — "
            f"run `launchctl bootout gui/{uid}/{label}` by hand and retry"
        )
    _launchctl(["bootstrap", domain, str(path)])
    _launchctl(["kickstart", "-k", f"{domain}/{label}"])


def kickstart(uid: int, label: str) -> None:
    """Restart the agent (`-k` kills the running copy first). The service must be
    loaded; `harness service install` is what loads it."""
    _launchctl(["kickstart", "-k", f"gui/{uid}/{label}"])


def unload(uid: int, label: str) -> bool:
    """Stop and forget the agent. True if it was loaded, False if it wasn't."""
    result = _launchctl(["bootout", f"gui/{uid}/{label}"], check=False)
    return result.returncode == 0


def status(uid: int, label: str) -> str | None:
    """`launchctl print` output for the agent, or None when it is not loaded."""
    result = _launchctl(["print", f"gui/{uid}/{label}"], check=False)
    if result.returncode != 0:
        return None
    return result.stdout
